### ISSUE TITLE
Initialize project and create Kanban Boards

### ISSUE THREAD

**Issue by tjay1760** [tjay1760/Recipe-app#15]
We are 2 contributors to this project @tjay1760  and @SAZZAD1Q2 
**Project link :** https://github.com/tjay1760/Recipe-app/projects/1

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @tjay1760 and @SAZZAD1Q2,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You should provide the link to your Kanban board, not your repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @tjay1760 and @SAZZAD1Q2,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well-assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly add the description now, instead later. Kindly do this for every other issue that may have this kind of vague description.

  ![image](https://github.com/tjay1760/Recipe-app/assets/36542986/9b9f355d-f7df-4ca4-bc72-40ba17d2945c)

- [ ] Kindly go through your requirements and include this task

  ![image](https://github.com/tjay1760/Recipe-app/assets/36542986/f1673c01-eadc-4523-90ff-cfd1b2ae71bf)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
### Hi @TedLivist 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![AmazingCreepyFrogmouth-max-1mb](https://user-images.githubusercontent.com/69077061/255314805-13569584-0c0e-4b38-a0bd-94d901ba8a1e.gif)




## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅


## Optional suggestions

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
